name: valorant_guide
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  path: ^1.8.3
  provider: ^6.0.5
  shared_preferences: ^2.2.2
  sqflite: ^2.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/agents/brimstone/
    - assets/agents/phoenix/
    - assets/agents/sage/
    - assets/agents/sova/
    - assets/agents/viper/
    - assets/agents/cypher/
    - assets/agents/reyna/
    - assets/agents/killjoy/
    - assets/agents/breach/
    - assets/agents/omen/
    - assets/agents/jett/
    - assets/agents/raze/
    - assets/agents/skye/    
    - assets/agents/yoru/  
    - assets/agents/astra/
    - assets/agents/kayo/
    - assets/agents/chamber/
    - assets/agents/neon/    
    - assets/agents/fade/
    - assets/agents/harbor/  
    - assets/agents/gekko/
    - assets/agents/deadlock/          
    - assets/roles/
  fonts:
    - family: Tungsten
      fonts:
        - asset: fonts/Tungsten-Bold.ttf