// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBbN3CLumPvWQnBP2zpeQ91S7PJBWsDGrA',
    appId: '1:864285724103:web:cf114ab62458bfe19e1de2',
    messagingSenderId: '864285724103',
    projectId: 'valorant-guide-88cd3',
    authDomain: 'valorant-guide-88cd3.firebaseapp.com',
    storageBucket: 'valorant-guide-88cd3.appspot.com',
    measurementId: 'G-C18MZ2VPQP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAWLzoOwoPtp0TIe6lQdnF_Bti_Q22Ivh8',
    appId: '1:864285724103:android:22fb8e4a143f940f9e1de2',
    messagingSenderId: '864285724103',
    projectId: 'valorant-guide-88cd3',
    storageBucket: 'valorant-guide-88cd3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBiBuqM11knWxNrQ1Eg6_1gU5pic_lR-sk',
    appId: '1:864285724103:ios:ea4850925b1da1179e1de2',
    messagingSenderId: '864285724103',
    projectId: 'valorant-guide-88cd3',
    storageBucket: 'valorant-guide-88cd3.appspot.com',
    iosBundleId: 'com.github.ssferraz.valorantGuide',
  );
}
